id: P000603
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12280
  title: ཀུན་རིག་གི་ཆོ་གའི་སྒྲུབ་སྐོར།
  author: ''
  volumes:
    69e7b10ab72746a6870d949b77323682:
      image_group_id: I1KG12413
      title: ''
      volume_number: 1
      total_pages: 396
