id: I31A2AB61
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:09:52+00:00'
last_modified: '2022-06-07T12:25:50.208520+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12280
  title: ཀུན་རིག་གི་ཆོ་གའི་སྒྲུབ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3073':
      image_group_id: I1KG12413
      title: ''
      total_pages: 396
      order: 1
      base_file: 3073.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
